### ISSUE TITLE
Put Janni inside Sphire

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-janni#1]
I think this should go inside SPHIRE, as it is crYOLO now, not another plugin.

**Comment by pconesa** [comment]
Hi! We thought about it but since there is no common code among cryolo and janni we decided to make another plugin and keeping them simple.

Additionally, janni releases will trigger this plugin releases and not cryolo. I rather, at least for now, keep it like this.

**Comment by delarosatrevin** [comment]
As you wish...I think machines will probably will running out of space with so many conda environments. 
This is from Thorsten on Twitter: https://twitter.com/pixelbaumarkt/status/1133463096490700800 I guess the same apply to JANNI.

**Comment by pconesa** [comment]
Thanks @delarosatrevin , we might rethink this then, but the "Right now" in thorsten tweeter is what concerns me.

**Comment by JorMaister** [comment]
Hi @thorstenwagner, 

Is it possible to know if JANNI and CrYOLO future developments are going to be able to be executed in one only Conda environment?

**Comment by thorstenwagner** [comment]
Hi @JorMaister !

Yes, crYOLO and JANNI can be in the same environment. Actually, JANNI is already a dependency of crYOLO and installed together with it.

**Comment by JorMaister** [comment]
Thank you, @thorstenwagner, for the quick response.
We will integrate it in Sphire then.
